### ISSUE TITLE
In Response class drop a lot of errors

### ISSUE THREAD

**Issue by zett93** [elberth90/yeelight-api-client#12]
Here is my code, it resolves all of erros, that I have.

class Response
```

public function __construct(array $response)
    {
	if (is_array($response))
	{
		if (isset($response['id']))
			$this->deviceId = $response['id'];
		else
			$this->deviceId = null;

	        if (isset($response['error'])) {
	            $this->exception = new BulbCommandException(
	                $response['error']['message'],
        	        $response['error']['code'],
        	        $response['id']
        	    );
       	 	} else if (isset($response['result'])) {
        		$this->result = $response['result'];
		} else {
			$this->result = [];
		}
	} else {
		$this->deviceId = null;
		$this->result = [];
	}
    }
```

maybe better will be if this should immedietly throw exception, but it works fine in my project ;)

**Comment by elberth90** [comment]
Hi, thanks for your suggestions and sorry for late response, I had a really long vacation ;) I will update project and most likely I will break backward compatibility.

**Comment by elberth90** [comment]
https://github.com/elberth90/yeelight-api-client/pull/14

**Comment by elberth90** [comment]
Did some changes in https://github.com/elberth90/yeelight-api-client/pull/14
