### ISSUE TITLE
How interface directly with a bulb knowing IP or ID?

### ISSUE THREAD

**Issue by sineverba** [elberth90/yeelight-api-client#13]
To simple operations I don't want every time make a full search.

I can save the IDs or IPs.

How can I call directly a bulb?

Thank you.

**Comment by elberth90** [comment]
Hi, sorry for a very late response, I had really long vacation. Current implementation of search
```
$client = new \Yeelight\YeelightClient();
$bulbList = $client->search();
```
return a map of bulbs where key is the IP address of the bulb. Additionaly each bulb has a `getId()` method so you can write custom search.

**Comment by sineverba** [comment]
Thank you and sorry now for my late response. I mean:

With search I can have a list of lamps/bulb, and this is ok.

Now I would only, for example, poweron only the 192.168.1.150. I don't need anymore search, 'cause I save in a table all ips, and I don't need a new search.

My question: 

I have the bulb on 192.168.1.150, how I can call this:

```
foreach ($bulbList as $bulb) {
    $promise = $bulb->getProp([\Yeelight\Bulb\BulbProperties::COLOR_TEMPERATURE]);
}
```

without the foreach? Or, in another point of view, how can i create a bulb object starting from an IP?

E.g., dummy code:

```
$bulb = new bulb('192.168.1.150');
$promise = $bulb->getProp([\Yeelight\Bulb\BulbProperties::COLOR_TEMPERATURE]);
```

**Comment by elberth90** [comment]
Hi @sineverba , well, my recommendation is to store somewhere `Bulb` object instance. However, you could use `Bulb` class constructor if you really need it. 
`public function __construct(Socket $socket, string $ip, int $port, string $id)`
Unfortunately, the `Bulb` class relly on the `Socket` object (not an interface ) from the `https://github.com/clue/socket-raw` library, so you will need to fulfill this need.
